//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athena.Resources.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlas.
        /// </summary>
        internal static string Atlas {
            get {
                return ResourceManager.GetString("Atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobook.
        /// </summary>
        internal static string Audiobook {
            get {
                return ResourceManager.GetString("Audiobook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        internal static string Comic {
            get {
                return ResourceManager.GetString("Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrimeStory.
        /// </summary>
        internal static string CrimeStory {
            get {
                return ResourceManager.GetString("CrimeStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culinary.
        /// </summary>
        internal static string Culinary {
            get {
                return ResourceManager.GetString("Culinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        internal static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string Fantasy {
            get {
                return ResourceManager.GetString("Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForChildren.
        /// </summary>
        internal static string ForChildren {
            get {
                return ResourceManager.GetString("ForChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatics.
        /// </summary>
        internal static string Informatics {
            get {
                return ResourceManager.GetString("Informatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageLearning.
        /// </summary>
        internal static string LanguageLearning {
            get {
                return ResourceManager.GetString("LanguageLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law.
        /// </summary>
        internal static string Law {
            get {
                return ResourceManager.GetString("Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistics.
        /// </summary>
        internal static string Linguistics {
            get {
                return ResourceManager.GetString("Linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonFiction.
        /// </summary>
        internal static string NonFiction {
            get {
                return ResourceManager.GetString("NonFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalDevelopment.
        /// </summary>
        internal static string PersonalDevelopment {
            get {
                return ResourceManager.GetString("PersonalDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosophy.
        /// </summary>
        internal static string Philosophy {
            get {
                return ResourceManager.GetString("Philosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        internal static string Poetry {
            get {
                return ResourceManager.GetString("Poetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation.
        /// </summary>
        internal static string Recreation {
            get {
                return ResourceManager.GetString("Recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        internal static string Romance {
            get {
                return ResourceManager.GetString("Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string Science {
            get {
                return ResourceManager.GetString("Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociology.
        /// </summary>
        internal static string Sociology {
            get {
                return ResourceManager.GetString("Sociology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBook.
        /// </summary>
        internal static string TextBook {
            get {
                return ResourceManager.GetString("TextBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        internal static string Thriller {
            get {
                return ResourceManager.GetString("Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourism.
        /// </summary>
        internal static string Tourism {
            get {
                return ResourceManager.GetString("Tourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoungAdult.
        /// </summary>
        internal static string YoungAdult {
            get {
                return ResourceManager.GetString("YoungAdult", resourceCulture);
            }
        }
    }
}
