//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langugaes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langugaes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athena.Resources.Langugaes", typeof(Langugaes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        internal static string Afrykanerski {
            get {
                return ResourceManager.GetString("Afrykanerski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ.
        /// </summary>
        internal static string Albański {
            get {
                return ResourceManager.GetString("Albański", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string Amharski {
            get {
                return ResourceManager.GetString("Amharski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string Angielski {
            get {
                return ResourceManager.GetString("Angielski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        internal static string Arabski {
            get {
                return ResourceManager.GetString("Arabski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZ.
        /// </summary>
        internal static string Azerski {
            get {
                return ResourceManager.GetString("Azerski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN.
        /// </summary>
        internal static string Bengalski {
            get {
                return ResourceManager.GetString("Bengalski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string Białoruski {
            get {
                return ResourceManager.GetString("Białoruski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string Bośniacki {
            get {
                return ResourceManager.GetString("Bośniacki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        internal static string Bretoński {
            get {
                return ResourceManager.GetString("Bretoński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG.
        /// </summary>
        internal static string Bułgarski {
            get {
                return ResourceManager.GetString("Bułgarski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZH.
        /// </summary>
        internal static string Chiński {
            get {
                return ResourceManager.GetString("Chiński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string Chorwacki {
            get {
                return ResourceManager.GetString("Chorwacki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        internal static string Czeski {
            get {
                return ResourceManager.GetString("Czeski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        internal static string Duński {
            get {
                return ResourceManager.GetString("Duński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EO.
        /// </summary>
        internal static string Esperanto {
            get {
                return ResourceManager.GetString("Esperanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        internal static string Estoński {
            get {
                return ResourceManager.GetString("Estoński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI.
        /// </summary>
        internal static string Fiński {
            get {
                return ResourceManager.GetString("Fiński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string Francuski {
            get {
                return ResourceManager.GetString("Francuski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL.
        /// </summary>
        internal static string Galicyjski {
            get {
                return ResourceManager.GetString("Galicyjski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL.
        /// </summary>
        internal static string Grecki {
            get {
                return ResourceManager.GetString("Grecki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE.
        /// </summary>
        internal static string Hebrajski {
            get {
                return ResourceManager.GetString("Hebrajski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        internal static string Hiszpański {
            get {
                return ResourceManager.GetString("Hiszpański", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string Holenderski {
            get {
                return ResourceManager.GetString("Holenderski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Inne {
            get {
                return ResourceManager.GetString("Inne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA.
        /// </summary>
        internal static string Irlandzki {
            get {
                return ResourceManager.GetString("Irlandzki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JA.
        /// </summary>
        internal static string Japoński {
            get {
                return ResourceManager.GetString("Japoński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string Kataloński {
            get {
                return ResourceManager.GetString("Kataloński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        internal static string Koreański {
            get {
                return ResourceManager.GetString("Koreański", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT.
        /// </summary>
        internal static string Litewski {
            get {
                return ResourceManager.GetString("Litewski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LV.
        /// </summary>
        internal static string Łotewski {
            get {
                return ResourceManager.GetString("Łotewski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK.
        /// </summary>
        internal static string Macedoński {
            get {
                return ResourceManager.GetString("Macedoński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string Malajski {
            get {
                return ResourceManager.GetString("Malajski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN.
        /// </summary>
        internal static string Mongolski {
            get {
                return ResourceManager.GetString("Mongolski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string Nepalski {
            get {
                return ResourceManager.GetString("Nepalski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string Niemiecki {
            get {
                return ResourceManager.GetString("Niemiecki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        internal static string Norweski {
            get {
                return ResourceManager.GetString("Norweski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string Polski {
            get {
                return ResourceManager.GetString("Polski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        internal static string Portugalski {
            get {
                return ResourceManager.GetString("Portugalski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RU.
        /// </summary>
        internal static string Rosyjski {
            get {
                return ResourceManager.GetString("Rosyjski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO.
        /// </summary>
        internal static string Rumuński {
            get {
                return ResourceManager.GetString("Rumuński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string Serbski {
            get {
                return ResourceManager.GetString("Serbski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH.
        /// </summary>
        internal static string Serbsko_Chorwacki {
            get {
                return ResourceManager.GetString("Serbsko-Chorwacki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        internal static string Słowacki {
            get {
                return ResourceManager.GetString("Słowacki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        internal static string Słoweński {
            get {
                return ResourceManager.GetString("Słoweński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string Suahili {
            get {
                return ResourceManager.GetString("Suahili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV.
        /// </summary>
        internal static string Szwedzki {
            get {
                return ResourceManager.GetString("Szwedzki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH.
        /// </summary>
        internal static string Tajski {
            get {
                return ResourceManager.GetString("Tajski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string Turecki {
            get {
                return ResourceManager.GetString("Turecki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        internal static string Ukraiński {
            get {
                return ResourceManager.GetString("Ukraiński", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CY.
        /// </summary>
        internal static string Walijski {
            get {
                return ResourceManager.GetString("Walijski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HU.
        /// </summary>
        internal static string Węgierski {
            get {
                return ResourceManager.GetString("Węgierski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VI.
        /// </summary>
        internal static string Wietnamski {
            get {
                return ResourceManager.GetString("Wietnamski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string Włoski {
            get {
                return ResourceManager.GetString("Włoski", resourceCulture);
            }
        }
    }
}
